### ISSUE TITLE
Switch to debian testing for newer dependencies

### ISSUE THREAD

**Issue by Susurrus** [jimmycuadra/docker-rust#10]
I've been using this image but recently ran into issues with the version of gtk included in Debian Jessie being too old (3.14) and I need newer (3.20). Debian testing has 3.22, so I was wondering if you'd be amenable to basing your image on Debian Testing instead of Jessie? I'm not asking that gtk packages be included, but at least then the packages I need would be available.

**Comment by jimmycuadra** [comment]
Sure, I'll give it some thought. Though generally, the purpose of this image is to help people interested in Rust get their feet wet. Once you start doing any serious development, you'd probably be better served by building an image specifically tailored to your application, or just installing Rust on your host system.

**Comment by Susurrus** [comment]
Are you still considering this? I'll close this issue if you aren't inclined to do this in the short term.

**Comment by jimmycuadra** [comment]
I think I'm going to leave the image as is for now, but thanks for asking!
